name: Metrics
on:
  schedule: 
    - cron: "0 0 * * 1"  # Runs every Monday
  workflow_dispatch:  # Allows manual triggering

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: "repositories"
          config_timezone: "Asia/Kolkata"
          plugin_languages: yes
          plugin_languages_ignored: "html, css, shell"
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
